all:
	make -C cryptdfu
	make -C cryptfirmware
	make -C cryptnor
	make -C decryptdfu
	make -C decryptfirmware
	make -C decryptnor
	make -C decrypt8720

clean:
	make -C cryptdfu clean
	make -C cryptfirmware clean
	make -C cryptnor clean
	make -C decryptdfu clean
	make -C decryptfirmware clean
	make -C decryptnor clean
